spring.application.name=TPass

spring.datasource.url=jdbc:postgresql://localhost:5432/tpassdb
spring.datasource.username=tpass-server
spring.datasource.password=2kCsOmBxvR82h6Y00nikCCE6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = tpass.support@gmail.com
spring.mail.password = thisPasswordShouldBeChanged

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=4000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=4000


logging.level.org.springframework.security=DEBUG
server.error.whitelabel.enabled=false
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

spring.session.jdbc.initialize-schema=always

server.servlet.session.cookie.name=TPASS_SESSION
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true

server.servlet.session.timeout=1d